SELECT CONCAT('/home/grep/src/', F.BOARD_ID, '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS F 
JOIN (SELECT BOARD_ID FROM USED_GOODS_BOARD
      WHERE VIEWS = (SELECT MAX(VIEWS) FROM USED_GOODS_BOARD)) AS B
ON F.BOARD_ID = B.BOARD_ID
ORDER BY FILE_ID DESC