WITH RECURSIVE H AS(
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR +1 FROM H
    WHERE HOUR < 23)

SELECT HOUR, COUNT(DATETIME) AS COUNT
FROM H LEFT JOIN ANIMAL_OUTS ON HOUR(DATETIME)=HOUR
GROUP BY HOUR
ORDER BY HOUR